"""Todas las constantes numéricas del juego. Ningún número mágico fuera de aquí."""

ENERGY_MAX = 20
ENERGY_REGEN_SECONDS = 360  # 1 punto cada 6 min → lleno en 2 h
ENERGY_COST_DUNGEON = 1

HP_REGEN_SECONDS = 120  # cada 2 min...
HP_REGEN_PERCENT = 0.02  # ...recupera un 2% de la vida máxima

XP_BASE, XP_EXPONENT = 40, 1.6
HP_BASE, HP_PER_LEVEL = 40, 12
ATK_BASE, ATK_PER_LEVEL = 6, 2
DEF_BASE, DEF_PER_LEVEL = 2, 1

DAMAGE_VARIANCE = (0.90, 1.10)
DEFENSE_K = 6  # constante de mitigación
CRIT_BASE_CHANCE = 5  # %
CRIT_MULTIPLIER = 1.8
FLEE_CHANCE = 0.6
MAX_TURNS = 40  # corta combates eternos

LOOT_CHANCE = 0.45
POTION_HEAL_PERCENT = 0.40
DEATH_GOLD_PENALTY = 0.10  # pierde el 10% del oro
DEATH_HP_RESTORE = 0.50

DAILY_GOLD, DAILY_POTIONS = 100, 2

STARTING_POTIONS = 3
LOG_LINES = 4  # líneas visibles del registro de combate

MONSTER_HP_BASE, MONSTER_HP_PER_LEVEL = 30, 14
MONSTER_ATK_BASE, MONSTER_ATK_PER_LEVEL = 5, 2.2
MONSTER_DEF_BASE, MONSTER_DEF_PER_LEVEL = 1, 0.8
MONSTER_LEVEL_SPREAD = (-1, 0, 0, 0, 1)

BOSS_EVERY_LEVELS = 5
BOSS_CHANCE = 0.35
BOSS_HP_MULTIPLIER = 1.6
BOSS_ATK_MULTIPLIER = 1.3
BOSS_REWARD_MULTIPLIER = 2.5

XP_REWARD_BASE, XP_REWARD_EXPONENT = 18, 1.2
GOLD_REWARD_RANGE = (8, 15)

ITEM_POWER_BASE, ITEM_POWER_PER_LEVEL = 2, 1.2
ITEM_POWER_VARIANCE = (0.9, 1.1)
WEAPON_CRIT_RANGE = (1, 5)
AMULET_CRIT_RANGE = (1, 3)
AMULET_ATK_SHARE = 0.5

POTION_PRICE = 50
SELL_PRICE_PER_LEVEL = 10
INVENTORY_PAGE_SIZE = 8

DAILY_COOLDOWN_SECONDS = 20 * 3600
RANKING_SIZE = 10
THROTTLE_SECONDS = 0.7
